### PR TITLE
Add dynamic height state (+ add test setup)

### LINKED ISSUE #133: Toast height calculation bug
Example: https://codesandbox.io/s/react-hot-toast-responsive-position-forked-64f33?file=/src/App.js

Screen Shot 2021-11-17 at 3 38 38 PM

When you use the toast ID to change one toast to another (e.g. from loading to success), sometimes the height of the toast is off. I think it's because it's not updating the height of the toast container when the content changed.

(As always, thank you for this great lib!)

### PR DESCRIPTION
**Pull request by timolins**
* Listen for height changes with `MutationObserver` - fixes #133 
* Fix #154 - thanks to @silvenon 
* Add testing setup

### CODE REVIEW

**Comment by themagickoala** [comment]
Am I right in thinking the only thing blocking this is the size-limit check? Anything we can do to help this along?

**Comment by timolins** [comment]
@themagickoala Indeed, and it feels weird to block it because of it. I think I'll just merge it for now.

There is #217 which would decrease bundle size below 5kb again.

Maybe even won't even hit 5kb as the check returns only `4944` bytes (but still fails?).

**Comment by themagickoala** [comment]
Thanks @timolins! Will there be a release going out with this soon? My current solution is to mock the library and test the toast method was called, and I'd love to get back to real userland testing.

**Comment by timolins** [comment]
Hi @themagickoala – sorry for the delay! I just released [2.4.0-beta.0](https://github.com/timolins/react-hot-toast/releases/tag/v2.4.0-beta.0), which includes those changes. Let me know how it works for you.

**Comment by themagickoala** [comment]
> Hi @themagickoala – sorry for the delay! I just released [2.4.0-beta.0](https://github.com/timolins/react-hot-toast/releases/tag/v2.4.0-beta.0), which includes those changes. Let me know how it works for you.

Hi @timolins just picked this up today and it looks like this does fix our tests. Thanks so much!

**Comment by themagickoala** [comment]
And thanks @silvenon for implementing this!

**Comment by silvenon** [comment]
Yay! 🎉

**Pull request merged**
