### PR TITLE
Enables toasts to be used with react components and elements

### PR DESCRIPTION
**Pull request by OlaoluwaM**
Instead of completely replacing the <Message> component, I thought it would be better to use it as a wrapper around whatever the user passes in their toast 

To achieve that I made some additions to the conditions of the 'isFunction' function so that it returns false whenever it encounters a react component or element. This way, if the 'resolvedValueOrFunction' function is passed a component or element (either function or class) it will simply return it as it was passed. 

What the conditional within the Message component does is check the type of the result from the 'resolvedValueOrFunction' function. If the result is a primitive value, it returns it; Also, if the result is a react element-which is a UI descriptor object-it is also returned since its type is not a function. However, if the result is a react component then it reconciles it.

The reason I used React.createElement instead of <DataToRender /> was because I was getting an error in the compiler. Nonetheless, since JSX compiles to React.createElement it should work.

### CODE REVIEW

**Comment by timolins** [comment]
Hey, thanks for your PR! I'm not entirely sure what issue this solves, other than adding a second API to create React toasts. Toasts are always displayed when dispatched, so I'm not sure if there is a benefit to pass a React component instead of the element. Am I missing something?

**Comment by OlaoluwaM** [comment]
Yh, from what I saw in the examples the toasts only accepted strings. So I made such that the toasts can also accept custom react components and elements

**Comment by OlaoluwaM** [comment]
Like how react-toastify allow you to, in addition to strings, pass your own react element or custom component. Or is that not what you wanted?

**Comment by timolins** [comment]
This is already possible :) You can find an example [here](https://react-hot-toast.com/docs/toast) (at the bottom) or on the homepage the _JSX Content_ example.

If you are referring to issue #13: the problem here is that while you can provide custom content, it's not possible to modify the wrapper. It has a padding which could be a problem if you try to provide a completely custom notification component.

**Comment by OlaoluwaM** [comment]
😂, sorry I didn't see that. Ok, for modifying the wrapper you could use CSS. You could move the styles for the Message component to a CSS file, make it a normal class (.Toast_Message_Wrapper), and add it to whatever wrapper that is passed by the user, along with any other DOM attributes. Will that help?

**Pull request closed without merging**
