### PR TITLE
Adding reduced motion media query to disable notification animations.

### PR DESCRIPTION
**Pull request by cbleslie**
Hey cool React Hot Toast people!

The problem:
Animations are cool. Sometimes; animations are less than ideal for some users. [MDN can explain this all the better](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion). Currently React Hot Toast's animations don't obey the reduced motion media query that responds to the user's OS.

How this PR addresses the a11y issue:
On the `ToastBar` component I have disabled the transitions and animations in the event that `prefers-reduced-motion` media query is enabled.

Please let me know if this is acceptable. Look forward to your feedback.

### CODE REVIEW

**Comment by cbleslie** [comment]
Hmm... goober not support media queries?

**Comment by cbleslie** [comment]
Closing this until I can figure out how this whole goober api works.

**Comment by timolins** [comment]
Great idea, thanks for bringing that up. However, it doesn't seem to work for me on the preview link. Does it work for you?

**Comment by cbleslie** [comment]
Hey @timolins , Try now. Please ensure you have reduced motion set in your OS settings <3.

**Comment by Kilian** [comment]
Looks good, I made a quick comparison for you:
https://user-images.githubusercontent.com/41970/107065944-a2b2eb00-67dd-11eb-9e60-a6dfd0d67b5c.mp4

**Comment by cbleslie** [comment]
@Kilian It looks good enough for me; Are you good with it?

**Comment by timolins** [comment]
That looks great already! One thing we should sort out is that the missing exit animation, causes them to stack for 1s. 

image

**Pull request closed without merging**
