### PR TITLE
fix: `matchMedia is not defined`

### PR DESCRIPTION
**Pull request by Dev-CasperTheGhost**
This PR fixes an error when using next.js SSR

### CODE REVIEW

**Comment by Dev-CasperTheGhost** [comment]
This should also fix this issue in tests:

Just add it in `toast.test.tsx`

```ts
Object.defineProperty(window, 'matchMedia', {
  value: () => {
    return {
      matches: false,
      addListener: () => {},
      removeListener: () => {},
    };
  },
});
```

**Comment by Dev-CasperTheGhost** [comment]
@timolins any news on this :D?

**Comment by aborza-c** [comment]
This is sorely needed. Also for gatsby, or any other SSR for that matter.

**Comment by timolins** [comment]
Thanks!

**Pull request merged**
