### PR TITLE
allow option to make toast unique

### PR DESCRIPTION
**Pull request by infothien**
First of all, thank you for very great Lib ! 

In my opinion, for some of cases, people might just want to display only 1 toast at a time instead of stacking them (I think it might be reasonable, since it will prevent distraction for the Users and user just only need to focus for the last appeared Toast).

The lib is easy to customizable to make it work but I also think maybe adding that as an option for the ToastOptions might be a better way and easier for future use ! That is why I made this pr.

So how do you think about it @timolins !

https://user-images.githubusercontent.com/30365498/112615276-a1a94c00-8e65-11eb-98d9-0a0e44cbd5e4.mov

### CODE REVIEW

**Comment by infothien** [comment]
https://github.com/timolins/react-hot-toast/pull/62, I also make a pr that could allow us to decide the animation for toast:
_ slide-{up, down, left, right}. Please also give it a check 🙇‍♂️

**Comment by infothien** [comment]
sorry @timolins also this one. Do you think any chances this pr could be merged ? Please let me know otherwise feel free to close it

**Comment by timolins** [comment]
Thanks for getting involved with react-hot-toast :) 

This proposal behaves differently than I expected. I assumed that unique meant that there can't be two of two toast of the same kind. However this is a bit more complex since you need to keep track which toast is actually a duplicate, instead of wiping all toasts.

By providing a fixed ID we can already have this behaviour:
```js
toast("I'm the one", {
  id: "only-one"
})
```


In case that you want only one toast globally, I'd except to configure this in the toaster itself. If you think there should be a `toastLimit` option one day, feel free to voice your opinion in this issue: https://github.com/timolins/react-hot-toast/issues/31

For now you can use this solution with `useEffect`:  https://github.com/timolins/react-hot-toast/issues/31#issuecomment-803359550

**Comment by infothien** [comment]
Oh thank you @timolins . I was not aware of that solution. Yeah I think your approach ToastLimit would be good enough indeed so I will go with it 👍

**Pull request closed without merging**
